# Generated by Django 3.1.7 on 2021-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
